<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-QMNBB7D" name="com.training.sanity.tests.HomePageTests" tests="5" failures="1" timestamp="14 May 2020 21:42:49 GMT" time="4.934" errors="0">
  <testcase name="veridyEditCustDet" time="4.934" classname="com.training.sanity.tests.HomePageTests">
    <failure type="java.lang.AssertionError" message="Modify Customer info failed expected [Success: You have modified customers!] but found [Success: You have modified customers!
×]">
      <![CDATA[java.lang.AssertionError: Modify Customer info failed expected [Success: You have modified customers!] but found [Success: You have modified customers!
×]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at com.training.sanity.tests.HomePageTests.veridyEditCustDet(HomePageTests.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- veridyEditCustDet -->
  <testcase name="verifyCartEdit" classname="com.training.sanity.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verifyCartEdit -->
  <testcase name="verifyCatagoryAddProduct" classname="com.training.sanity.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verifyCatagoryAddProduct -->
  <testcase name="verify" classname="com.training.sanity.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verify -->
  <testcase name="verifyReturnProduct" classname="com.training.sanity.tests.HomePageTests">
    <skipped/>
  </testcase> <!-- verifyReturnProduct -->
</testsuite> <!-- com.training.sanity.tests.HomePageTests -->
